site_name: Flutter快速开发手册
theme: material
repo_url: https://github.com/fuuqiu/mdFlutter
copyright:  Email:Fuuqiu@gmail.com </br> 支持提供优化方案
site_description: Fuuqiu编写的开发常用工具快速使用笔记 
site_author: Fuuqiu@gmail.com
